// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef animate_h
#define animate_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win;
#include <FL/Fl_Button.H>
int main();
#endif
